title: "Akylas Stratigakos"
name: "Akylas Stratigakos"
email: "a.stratigakos@ucl.ac.uk"
description: "Akylas Stratigakos is a Lecturer in Energy Systems and Data Analytics at UCL, working on machine learning, optimization, and low-carbon energy systems."

url: "https://akylasstrat.github.io"
baseurl: ""   # must match the repo name with a leading slash

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  # - jekyll-scholar

# markdown: kramdown
# permalink: /:categories/:title/

# plugins:
#  - jekyll-feed
#  - jekyll-sitemap
#  - jekyll-seo-tag
#  - jekyll-scholar

#scholar:
#  source: ./_bibliography
#  bibliography: papers.bib
#  style: apa
#  sort_by: year
#  order: descending
#  # Optional: use our custom item template below
#  bibliography_template: bib


# collections:
#   talks:
#     output: true
#     permalink: /talks/:name/

